// tags/team/index.jsx
import React from 'react'

import css from './index.module.scss'

export default () => {

	const list = [
		// {
		// 	picture: '/img/team/01.jpg',
		// 	name: 'Антон',
		// 	position: 'Директор'
		// },
		{
			picture: '/img/team/04.jpg',
			name: 'Яков',
			position: 'Специалист по тонировке'
		},
		{
			picture: '/img/team/01.jpg',
			name: 'Владимир',
			position: 'Специалист по тонировке'
		},
		{
			picture: '/img/team/02.jpg',
			name: 'Александр',
			position: 'Детейлинг-мастер'
		},
		{
			// picture: '/img/team/01.jpg',
			name: 'Сергей',
			position: 'Специалист по перетяжке салона'
		},
	]

	return (
		<div className={css.team}>
			<div className={css.inner}>

				<h2 className={css.title}>Наша команда</h2>

				<div className={css.list}>
					{list.map((val, key) => (
						<div key={key} className={css.item}>

							{val.picture && (
								<img className={css.img} src={val.picture} />
							)}

							<div className={css.name}>
								{val.name}
							</div>

							<div className={css.position}>
								{val.position}
							</div>

						</div>
					))}
				</div>

			</div>
		</div>
	)
}

// components/team/team.vue
<template>
	<div class='team'>
		<div class='container'>
		
			<h2 class='team-title'>Наша команда</h2>
			
			<div class="team-inner">

				<div v-for='(item, i) in list' :key='i' class='team-item'>
					<div class='team-item-img' :style='`background-image: url(${item.picture});`'>
					</div>
					<div class='team-item-name'>
						{{item.name}}
					</div>
					<div class='team-item-position'>
						{{item.position}}
					</div>
				</div>
				
			</div>
		</div>
	</div>
</template>

<script>

	export default {
		
		name: 'team',

		data() {
			return {
				list: [
					{
						picture: '',
						name: 'Антон',
						position: 'Директор'
					},
					{
						picture: '',
						name: 'Яков',
						position: 'Специалист по тонировке'
					},
					{
						picture: '',
						name: 'Владимир',
						position: 'Специалист по тонировке'
					},
					{
						picture: '',
						name: 'Александр',
						position: 'Детейлинг-мастер'
					},
					{
						picture: '',
						name: 'Сергей',
						position: 'Специалист по перетяжке салона'
					},
				]
			}
		}
	}
</script>
