// pages/service/alarm.vue
<template>
	<div>

		<Head
			title='Установка автосигнализаций'
			text='100% защита вашего авто'
			thumb='/img/full/alarm.jpg'
			/>

		<Edge
			:list="[
				{
					img: '/img/edge-01.svg',
					value: 'Безопасно',
					label: 'Индивидуальный подбор наиболее эффективных пленок',
				},
				{
					img: '/img/edge-02.svg',
					value: 'Экологично',
					label: 'Работаем с лучшими брендами: ***********',
				},
				{
					img: '/img/edge-03.svg',
					value: 'Гарантия',
					label: 'Гарантия качества и сроков выполнения',
				},
			]"
			/>

		<Steps
			:list="[
				{
					value: '',
					label: '',
					thumb: '/img/step/alarm/01.jpg'
				},
				{
					value: '',
					label: '',
					thumb: '/img/step/alarm/01.jpg'
				},
				{
					value: '',
					label: '',
					thumb: '/img/step/alarm/01.jpg'
				},
			]"
			/>

		<About
			:list="[
				{
					index: 1,
					value: 'Звонок или заявка',
					label: 'Вы можете записаться к нам на услугу через сайт'
				},
				{
					index: 2,
					value: 'Согласование времени',
					label: 'Мы выбираем свободное и удобное для вас время'
				},
				{
					index: 3,
					value: 'Прием авто в работу',
					label: 'Консультирование и прием автомобиля в работу'
				},
				{
					index: 4,
					value: 'Возвращаем авто',
					label: 'После качественно выполенной работы вы забираете автомобиль'
				}
			]"
			/>

		<price
			title="установки сигнализации"
			label="Выберите класс автомобиля:"
			:list="[
				{
					label: 'Малый',
					value: 'малый',
					price: 5000,
				},
				{
					label: 'Средний',
					value: 'средний',
					price: 7000,
				},
				{
					label: 'Внедорожники',
					value: 'внедорожники',
					price: 10000,
				},
				{
					label: 'Премиум',
					value: 'премиум',
					price: 10000,
				},
			]"
			/>

		<profit
			:list="[
				{
					label: '+90%',
					value: 'Продлевает срок службы ЛКП автомобиля'
				},
				{
					label: '-75%',
					value: 'Вероятность механического и химического воздействия'
				},
				{
					label: '1 год',
					value: 'Гарантируем качество и долгий срок службы бронирования'
				},
				{
					label: '99%',
					value: 'Клиентов рекомендуют нас друзьям'
				},
			]"
			/>

		<Insta keys='сигнализация' />

		<Result title="Установка автосигнализаций" image="/img/results/alarm.jpg">
			<p>Мы устанавливаем различные системы, от самых простых со стандартным набором функций, до самых сложных телематических устройств с максимальным набором охранных и пользовательских функций. Установка таких систем охраны требует от мастера максимальных знаний, таких как устройство автомобиля, возможности сигнализаций, методы и способы подключения. Установка охранных систем должна быть осуществлена максимально профессионально. От качества монтажа зависит правильность работы многих режимов, таких как автоматический запуск, по температуре двигателя, режим анти ограбления —  автомобиль должен правильно остановиться и подать сигнал об угоне, даже настройка датчика удара требует определенных навыков.</p>
		</Result>

		<team />

		<gmap />

	</div>
</template>

// pages/services/alarm.jsx
import { NextSeo } from 'next-seo'
import Link from 'next/link'

import Modal from '../../forms/call'

import Header from '../../tags/header'
import Footer from '../../tags/footer'

import Head from '../../tags/head'
import Edge from '../../tags/edge'
import Steps from '../../tags/steps'
import About from '../../tags/about'
import Price from '../../tags/price'
import Profit from '../../tags/profit'
import Insta from '../../tags/insta'
import Result from '../../tags/result'
import Team from '../../tags/team'
import Map from '../../tags/map'

const SEO = {
	title: 'Установка сигнализации на автомобиль в Омске',
	keywords: 'Установка сигнализации авто Омск',
	description: 'Компания «AvtoLife» оказывает услуги по установке сигнализаций на автомобили в Омске. Мы устанавливаем различные типы сигнализаций – от простых до самых сложных телематических устройств',
}

export default () => {

	return (
		<>

			<NextSeo {...SEO} />

			<Header />

			<Head
				title='Установка сигнализаций'
				text='защита вашего авто'
				thumb='/img/full/alarm.jpg'
				action='Расчитать стоимость'
			/>

			<Edge
				list={[
					{
						img: '/img/edge-01.svg',
						value: 'Безопасно',
						label: 'Индивидуальный подбор наиболее эффективных систем безопасности',
					},
					{
						img: '/img/edge-02.svg',
						value: 'Технологично',
						label: 'Работаем с лучшими брендами: Pandora, StarLine, Pantera',
					},
					{
						img: '/img/edge-03.svg',
						value: 'Гарантия',
						label: 'Гарантия качества и сроков выполнения',
					}
				]}
			/>

			<Steps
				list={[
					{
						value: 'Диагностика состояния авто',
						label: 'Оценка общего состояния кузова и подготовка поверхностей к работе.',
						thumb: '/img/step/alarm/01.jpg'
					},
					{
						value: 'Поклейка пленкой необходимые участки кузова',
						label: 'Производится качественная поклейка бронировочной пленки по поверхности кузова авто.',
						thumb: '/img/step/alarm/01.jpg'
					},
					{
						value: 'Проверка качества выполненных работ',
						thumb: '/img/step/alarm/01.jpg'
					}
				]}
			/>

			<About />

			<Price
				title="Узнать стоимость установки"
				list={[
					{
						title: 'Выберите класс авто:',
						list: [
							{
								thumb: '',
								label: 'Комплекс 1',
								value: 12500
							},
						]
					}
				]}
			/>

			<Profit
				list={[
					// {
					// 	label: '+99%',
					// 	value: 'Продлевает срок службы ЛКП автомобиля'
					// },
					// {
					// 	label: '-99%',
					// 	value: 'Вероятность сколов и порчи ЛКП в местах нанесения пленки'
					// },
					{
						label: '1 год',
						value: 'Гарантируем качество и долгий срок службы сигнализации'
					},
					{
						label: '99%',
						value: 'Клиентов рекомендуют нас друзьям'
					}
				]}
			/>

			<Insta keys="сигнал" />

			<Result title="Установка автосигнилизаций" thumb="/img/results/alarm.jpg">
				<p>Установка сигнализации сложный процесс предполагающий внедрение дополнительного блока управления в штатную проводку автомобиля, при этом не изменяется алгоритм работы электронных приборов, все подключения осуществляются параллельно исполнительным устройствам автомобиля.</p>
				<p>Мы устанавливаем различные системы, от самых простых со стандартным набором функций, до самых сложных телематических устройств с максимальным набором охранных и пользовательских функций. Установка таких систем охраны требует от мастера максимальных знаний, таких как устройство автомобиля, возможности сигнализаций, методы и способы подключения. Установка охранных систем должна быть осуществлена максимально профессионально. От качества монтажа зависит правильность работы многих режимов, таких как автоматический запуск, по температуре двигателя, режим анти ограбления —  автомобиль должен правильно остановиться и подать сигнал об угоне, даже настройка датчика удара требует определенных навыков.</p>
			</Result>

			<Team />

			<Map />
			
			<Footer />

		</>
	)
}
