// components/profit/profit.vue
<template>
	<div class="profit">
		<div class="container">
		
			<h2 class="profit-title">Почему это выгодно?</h2>
			
			<div class="profit-inner">

				<div v-for="(item, i) in list" :key="i" class="profit-item">
					<div class="profit-item-inner">
						<div class="profit-item-value">{{item.label}}</div>
						<div class="profit-item-label">{{item.value}}</div>
					</div>
				</div>

			</div>

			<div v-if="hint" class="profit-hint">
				<span>*</span> {{hint}}
			</div>

			<Action className='profit-call' action="Заказать звонок" />

		</div>
	</div>
</template>

<script>

	export default {
		
		name: 'profit',

		props: ['list', 'hint']

	}
</script>

// tags/profit/index.jsx
import React from 'react'

import Modal from '../../forms/call'

import css from './index.module.scss'

export default function Profit({ list = [], hint }) {

	return (
		<div className={css.container}>

			<h2 className={css.title}>Почему это выгодно?</h2>

			<div className={css.list}>
				{list.map((val, key) => (
					<div key={key} className={css.item}>
						<div className={css.inner}>

							<div className={css.label}>
								{val.label}
							</div>

							<div className={css.value}>
								{val.value}
							</div>

						</div>
					</div>
				))}
			</div>

			{hint && (
				<div className={css.hint}>
					<span>*</span> {hint}
				</div>
			)}

			<div className={css.call}>
				<Modal action="Записаться" />
			</div>

		</div>
	)
}
