// pages/services/tinting-auto.jsx
import { NextSeo } from 'next-seo'
import Link from 'next/link'

import Modal from '../../forms/call'

import Header from '../../tags/header'
import Footer from '../../tags/footer'

import Head from '../../tags/head'
import Edge from '../../tags/edge'
import Steps from '../../tags/steps'
import About from '../../tags/about'
import Price from '../../tags/price'
import Profit from '../../tags/profit'
import Insta from '../../tags/insta'
import Result from '../../tags/result'
import Team from '../../tags/team'
import Map from '../../tags/map'

const SEO = {
	title: 'Автоматическая тонировка авто в Омске',
	keywords: 'Автоматическая тонировка авто Омск',
	description: 'Компания «AvtoLife» оказывает услуги по автоматической тонировке авто в Омске. Автоматическая тонировка осуществляется нажатием кнопки за счет установки дополнительного затемненного стекла',
}

export default () => {

	return (
		<>

			<NextSeo {...SEO} />

			<Header />

			<Head
				title='Автоматическая тонировка'
				text='установка 2-х стекол на Ваш авто'
				thumb='/img/full/tinting-auto.jpg'
				action='Расчитать стоимость'
			/>

			<Edge
				list={[
					{
						img: '/img/edge-01.svg',
						value: 'Безопасно',
						label: 'Индивидуальный подбор наиболее эффективных механизмов',
					},
					{
						img: '/img/edge-02.svg',
						value: 'Технологично',
						label: 'Работаем с лучшими брендами: *********',
					},
					{
						img: '/img/edge-03.svg',
						value: 'Гарантия',
						label: 'Гарантия качества и сроков выполнения',
					}
				]}
			/>

			{/* <Steps
				list={[
					{
						value: 'Диагностика состояния салона',
						label: 'Оценка общего состояния салона, выявляются особо загрязненные участки салона.',
						thumb: '/img/step/tinting-auto/01.jpg'
					},
					{
						value: 'Подготовка и уборка салона автомобиля',
						label: 'Сухая в влажная уборка салона с применением максимально эффективных стредств для чистки.',
						thumb: '/img/step/tinting-auto/01.jpg'
					},
					{
						value: 'Сушка салона и проверка качества выполненных работ',
						thumb: '/img/step/tinting-auto/01.jpg'
					}
				]}
			/> */}

			<About />

			<Price
				title="Узнать стоимость установки автоматической тонировки"
				label="Выберите тип автомобиля:"
				list={[
					{
						thumb: '',
						label: 'Отечественная',
						value: 50000,
					},
					{
						thumb: '',
						label: 'Иномарка',
						value: 50000,
					}
				]}
			/>

			<Profit
				list={[
					{
						label: '+60%',
						value: 'ТС выглядит более презентабельно'
					},
					{
						label: '-75%',
						value: 'Содержимое салона скрыто от посторонних глаз'
					},
					{
						label: '1 год',
						value: 'Гарантируем качество и долгий срок службы бронирования'
					},
					{
						label: '99%',
						value: 'Клиентов рекомендуют нас друзьям'
					}
				]}
			/>

			<Insta keys="автоматическая" />

			<Result title="Автоматическая тонировка" thumb="/img/results/tinting-auto.jpg">
				<p>Автоматическая тонировка стекол – это современное решение, ставшее доступными потребителям лишь в последние несколько лет. С помощью одного нажатия кнопки, стекла в автомобиле буквально за несколько секунд становятся затемненными. Секрет довольно прост – в боковые дверцы водителя и пассажира устанавливаются два стекла, одно из которых тонированное. Ключевым фактором при расчете цены на автоматическую тонировку, является класс машины, сложность свеклоподъемного механизма и соответственно стоимость дополнительных стекол. На сегодняшний день в Омске имеется возможность установки автоматической тонировки практически на все популярные модели авто.</p>
			</Result>

			<Team />

			<Map />
			
			<Footer />

		</>
	)
}

// pages/service/tinting-auto.vue
<template>
	<div>

		<Head
			title='Автоматическая тонировка'
			text='установка 2-х стекол на Ваш авто'
			thumb='/img/full/tinting-auto.jpg'
			/>

		<Edge
			:list="[
				{
					img: '/img/edge-01.svg',
					value: 'Безопасно',
					label: 'Индивидуальный подбор наиболее эффективных пленок',
				},
				{
					img: '/img/edge-02.svg',
					value: 'Экологично',
					label: 'Работаем с лучшими брендами: ***********',
				},
				{
					img: '/img/edge-03.svg',
					value: 'Гарантия',
					label: 'Гарантия качества и сроков выполнения',
				},
			]"
			/>

		<Steps
			:list="[
				{
					value: '',
					label: '',
					thumb: '/img/step/tinting-auto/01.jpg'
				},
				{
					value: '',
					label: '',
					thumb: '/img/step/tinting-auto/01.jpg'
				},
				{
					value: '',
					label: '',
					thumb: '/img/step/tinting-auto/01.jpg'
				},
			]"
			/>

		<About
			:list="[
				{
					index: 1,
					value: 'Звонок или заявка',
					label: 'Вы можете записаться к нам на услугу через сайт'
				},
				{
					index: 2,
					value: 'Согласование времени',
					label: 'Мы выбираем свободное и удобное для вас время'
				},
				{
					index: 3,
					value: 'Прием авто в работу',
					label: 'Консультирование и прием автомобиля в работу'
				},
				{
					index: 4,
					value: 'Возвращаем авто',
					label: 'После качественно выполенной работы вы забираете автомобиль'
				}
			]"
			/>

		<price
			title="установки автоматической тонировки"
			label="Выберите тип автомобиля:"
			:list="[
				{
					label: 'Отечественная',
					value: 'Отечественная',
					price: 30000,
				},
				{
					label: 'Иномарка',
					value: 'Иномарка',
					price: 35000,
				},
			]"
			/>

		<profit
			:list="[
				{
					label: '+60%',
					value: 'ТС выглядит более презентабельно'
				},
				{
					label: '-75%',
					value: 'Содержимое салона скрыто от посторонних глаз'
				},
				{
					label: '1 год',
					value: 'Гарантируем качество и долгий срок службы бронирования'
				},
				{
					label: '99%',
					value: 'Клиентов рекомендуют нас друзьям'
				},
			]"
			/>

		<Insta keys='автоматическая' />

		<Result title="Автоматическая тонировка" image="/img/results/tinting-auto.jpg">
			<p>Автоматическая тонировка стекол – это современное решение, ставшее доступными потребителям лишь в последние несколько лет. С помощью одного нажатия кнопки, стекла в автомобиле буквально за несколько секунд становятся затемненными. Секрет довольно прост – в боковые дверцы водителя и пассажира устанавливаются два стекла, одно из которых тонированное. Ключевым фактором при расчете цены на автоматическую тонировку, является класс машины, сложность свеклоподъемного механизма и соответственно стоимость дополнительных стекол. На сегодняшний день в Омске имеется возможность установки автоматической тонировки практически на все популярные модели авто.</p>
		</Result>

		<team />

		<gmap />

	</div>
</template>

<script>
	export default {
		head: {
			title: 'Автоматическая тонировка авто в Омске',
			meta: [
				{
					name: 'keywords',
					content: 'Автоматическая тонировка авто Омске'
				},
				{
					name: 'description',
					content: 'Компания «Avto-Life» оказывает услуги по автоматической тонировке авто в Омске. Автоматическая тонировка осуществляется нажатием кнопки за счет установки дополнительного затемненного стекла'
				}
			],
		}
	}
</script>
